CREATE TABLE opciones (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenMesa1 (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenMesa2 (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenMesa3 (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenMesa4 (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenMesa5 (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenMesa6 (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenMesa7 (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenMesa8 (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

-- TABLA PARA ordenes_currentes

CREATE TABLE ordenes_currentes (
  id INT NOT NULL AUTO_INCREMENT,
  mesa VARCHAR(255) NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenes_listas (
  id INT NOT NULL AUTO_INCREMENT,
  mesa VARCHAR(255) NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ordenes_finalizadas (
  id INT NOT NULL AUTO_INCREMENT,
  mesa VARCHAR(255) NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  cantidad VARCHAR(255) NOT NULL,
  preciou VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);
